name: book_reader
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^8.1.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  html: ^0.15.4
  requests: ^4.7.0
  flutter_downloader: ^1.11.7
  flutter_inappwebview: ^6.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  realm: ^1.2.0
  uuid: ^4.4.0
  epub_view: ^3.2.0
  http: ^0.13.4
  flutter_pdfview: ^1.3.2
  image: ^3.3.0
  file_picker: ^8.0.3
  device_info_plus: ^10.1.0
  archive: ^3.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/genre_icons/
